apiVersion: v1
data:
  haproxy.cfg: |-
    global
      log 127.0.0.1 local0 
      maxconn 100
      pidfile /run/haproxy.pid
    
    defaults
      log	global
      mode	http
      option	httplog
      option	dontlognull
      timeout connect 5000
      timeout client  50000
      timeout server  50000

    frontend ingress-controller 
      bind 0.0.0.0:8086
      option forwardfor
    
      http-request allow
    
      default_backend ingress-controller

     frontend ingress-controller-80 
      bind 0.0.0.0:80
      option forwardfor
    
      http-request allow
    
      default_backend ingress-controller

    backend ingress-controller 
      balance roundrobin
      option forwardfor
      server ingress-controller-svc 10.254.0.80:80 check
  test.lst: |-
    1.189.209.20
    123.166.192.241
  watch.lst: haproxy.cfg white.ip.lst test.lst
  white.ip.lst: |-
    218.7.221.89
    123.166.205.24
    43.225.211.115
    113.0.235.117
    1.189.59.15
    43.225.211.50
    117.33.49.248
    43.225.211.37
    117.136.57.145
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: filtre
